spring.application.name=filmorate
logging.level.com.practice.filmorate.controller=debug

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./db/filmorate-diana
spring.datasource.username=sa
spring.datasource.password=password
spring.sql.init.mode=always
spring.h2.console.enabled=true